version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
  envoy:
    build:
      context: ./edge-envoy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - app
